# Generated by Django 5.2.4 on 2025-08-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_book_options_book_cover_image_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
